<?php

/**
 * Implements hook_menu().
 */
function jobportal_menu() {
  $items['offers/add'] = array(
		'title' => t('Add Job Offer'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('jobportal_add_offer_form'),
		'access callback' => TRUE,
		'file' => 'jobportal_add_offer.pages.inc',
  );
  $items['test'] = array(
		'title' => t('Test Page'),
		'page callback' => 'jobportal_test_page',
		'access callback' => TRUE,
  );
  return $items;
}

function jobportal_test_page() {
	//global $user;
	//var_dump($user->uid);
	$content['raw-markup'] = array(
		'#type' => 'markup',
		'#markup' => '<a href="offers/add/"><button style="width:200px; height:50px;">Hello World!</button></a>',
	);
	return $content;
}
